#!/bin/bash

# extracts authors from an SVN repository
# creates a boilerplate authors.txt file
# to be used by git-svn

set -e

if [ ! $# -eq 1 ];
then
  echo "Usage:"
  echo "$0 <config-file>"
  exit 1
fi

SVN_URL="$1"
DEST_FILE=authors.txt

if [ -e ${DEST_FILE} ];
then
  echo "${DEST_FILE} already exists - not overwriting"
  exit 1
fi

svn log -q "${SVN_URL}" | \
  awk -F '|' '/^r/ {sub("^ ", "", $2); sub(" $", "", $2); print $2" = "$2" "}' \
  | sort -u > "${DEST_FILE}"

